config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'sessions/new'
  root 'application#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  get    'search'   => 'users#search'
  get    'users/search'   => 'users#search_user'
  get    'rooms/search'   => 'rooms#search_room'
  get 'users/history' => 'users#get_history'
  get '/rooms/schedule_room/:id' => 'rooms#schedule_room'
  get '/users/booking_history/:id' => 'users#booking_history'
  resources :bookings
  resources :rooms
  resources :users
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  include SessionsHelper
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    if logged_in_as_admin?
    @bookings = Booking.where("cancelled =?",'f')
    else
      @bookings = Booking.where("user_id =?",session[:user_id])
      end
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.booked_by = User.find(session[:user_id]).name
    if(!@booking.user_id)
    @booking.user_id = session[:user_id]
    end
    #@allbookings = Booking.where("room_id= ?","#{booking_params[:room_id]}")
    if(@booking.booking> Time.now + 7.days || @booking.booking < Time.now)
     respond_to do |format|
      format.html { redirect_to new_booking_path ,notice: "Check your dates. Bookings cannot be made for the past or beyond 7 days from now!!"}
      format.json { render json: @booking.errors, status: :unprocessable_entity }
     end
      return
    end
    @allbookings = Booking.where("cancelled =? AND room_id= ?",'f',"#{booking_params[:room_id]}")
    @allbookings.each do |book|

          if (@booking.booking>=(book.booking) && @booking.booking<=(book.booking+2.hours))
            respond_to do |format|
            format.html { redirect_to new_booking_path ,notice: "Room booked at this time. Choose another room/time."}
            format.json { render json: @booking.errors, status: :unprocessable_entity }
            end
            return
          end
    end
    @allBookingsUser = Booking.where("cancelled =? AND user_id= ?",'f',"#{session[:user_id]}")
    @allBookingsUser.each do |book|
      if (!logged_in_as_admin? && book.booking>=Time.now - 2.hours)
        respond_to do |format|
          format.html { redirect_to new_booking_path ,notice: "Please get in touch with admin to reserve another room.You have a current booking!!"}
          format.json { render json: @booking.errors, status: :unprocessable_entity }
        end
        return
      end
    end
    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :'bookings/new' ,notice: 'Room booked at this time. Choose another room.'}
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
   # booking_params[:booked_by] = session[:user_id]
   if logged_in?
    if booking_params[:cancelled] == '1' && @booking.cancelled == false
      booking_params[:cancelled_by] = User.find(session[:user_id]).name
    end
    @allbookings = Booking.where("cancelled =? AND room_id= ?",'f',"#{booking_params[:room_id]}")
    @allbookings.each do |book|

      if (@booking.booking>=(book.booking) && @booking.booking<=(book.booking+3.hours)&& booking_params[:cancelled]=='0')
        respond_to do |format|
          format.html { redirect_to @booking ,notice: "Room booked at this time. Choose another room/time."}
          format.json { render json: @booking.errors, status: :unprocessable_entity }
        end
        return
      end
    end

    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
     else redirect_to_home
  end
end
  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:id,:user_id, :room_id ,:booking, :cancelled_by, :cancelled, :booked_by)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(booking,:html => {:class => 'form'}) do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div style = "margin: 10%">
  <div class="form-group">
    <%= f.label "When?" %>
    <%= f.datetime_select(:booking,:minute_step=> 30,:class => 'form-control') %>
  </div>

    <div class="form-group">
      <%= f.label :room_id %>
        <%= select("booking", "room_id", Room.all.collect{ |c| [ c.number , c.id] },{},{ :class => 'form-control'}) %></div>

  <div class="form-group">
    <%= f.label :cancelled %>
    <%= f.check_box(:cancelled) %>
  </div>

    <% if logged_in_as_admin?%>
    <div class="form-group">
      <%= f.label :user_id %>
      <%= select("booking", "user_id", User.all.collect{ |c| [ c.name, c.id] },{},{ :class => 'form-control' }) %>
    </div>


  <div class="form-group">
    <%= f.label :cancelled_by %>
    <%= f.text_field(:cancelled_by,class:"form-control") %>
  </div>



  <div class="form-group">
    <%= f.label :booked_by %>
    <%= f.text_field(:booked_by,class:"form-control") %>
  </div>
  <% end%>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<br/>
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Booking Time</th>
      <th>User</th>
      <th>Room</th>
      <!--<th>Cancelled by</th>-->
      <th>Cancelled</th>
      <th>Booked by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.booking %></td>
        <td><%= (User.find(booking.user_id)).name %></td>
        <td><%= (Room.find(booking.room_id)).number %></td>
        <td><%= booking.cancelled %></td>
        <td><%= booking.booked_by%></td>
        <td><%= link_to 'Show', booking %></td>
        <%if(session[:user_id] == booking.user_id)||logged_in_as_admin?%>
        <td><%= link_to 'Edit/Cancel', edit_booking_path(booking) %></td>

        <td><%= button_to 'Release', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<br/>
<b><p id="notice"><%= notice %></p></b>
<% if logged_in? %>
<%= render 'form', booking: @booking %>
<%else %>
    <%= link_to "Login to continue", sessions_new_path %></li>
<% end %>
<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<br/>
<p id="notice"><%= notice %></p>

<p>
  <strong>Booking:</strong>
  <%= @booking.booking %>
</p>


<!--<p>
  <strong>Cancelled by:</strong>
  %= @booking.cancelled_by %>
</p>-->


<p>
  <strong>Booked by:</strong>
  <%= @booking.booked_by %>
</p>
<% if  @booking.cancelled %>
<p>
  <strong>Cancelled:</strong>
  <%= @booking.cancelled %>
</p>
    <% end %>

<!-- %= link_to 'Edit', edit_booking_path(@booking) %> |-->
<%= link_to 'Back', bookings_path %>