config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'sessions/new'
  root 'application#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  get    'search'   => 'users#search'
  get    'users/search'   => 'users#search_user'
  get    'rooms/search'   => 'rooms#search_room'
  get 'users/history' => 'users#get_history'
  get '/rooms/schedule_room/:id' => 'rooms#schedule_room'
  get '/users/booking_history/:id' => 'users#booking_history'
  resources :bookings
  resources :rooms
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  attr_accessor :current_password, :new_password, :confirm_new_password
  before_update :check_password
  has_secure_password
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
# #TODO can put more validation for password strength
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  private
  def check_password
    is_ok = self.password.nil? || self.password.empty? || self.password.length >= 6

    self.errors[:password] << "Password is too short (minimum is 6 characters)" unless is_ok

    is_ok # The callback returns a Boolean value indicating success; if it fails, the save is blocked
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :set_user, only: [:show,:edit,:booking_history,:update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if logged_in_as_admin?
      @users = User.all.order(:is_admin)
      @count =@users.count
    else
      #Invalid or no cookie recieved in request, flash error
      redirect_to_home
    end
  end
  # GET /users/1
  # GET /users/1.json
  def show
    if !logged_in?
      #Invalid or no cookie recieved in request, flash error
      flash.now[:danger] = 'Please login to continue'
      render 'sessions/new'
      end
    else if logged_in_as_admin? || @current_user.id == params[:id]
      if params[:id]!= nil
        @user = User.find(params[:id])
      end
  end
end
  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if params[:id]!= nil
      @user = User.find(params[:id])
    end
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)
    if(!@user.is_admin)
      @user.is_admin = false
    end
    @user.is_root = false
    if(User.all.count == 0)
      @user.is_admin = true
      @user.is_root = true
    end
    respond_to do |format|
      if @user.save
        if logged_in?
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { redirect_to "/", notice: 'User was successfully created.' }
        end
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @bookingsForUser = Booking.where("user_id = ?","#{@user.id}")
    @bookingsForUser.each do|bookie|
      bookie.destroy
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #GET /rooms/1/schedule_room
  def booking_history
    @bookingUser = Booking.where("user_id =?","#{@user.id}").order(:booking)
  end
  def search_user
    if !logged_in_as_admin?
      #Invalid or no cookie recieved in request, flash error

      redirect_to_home
    end
    if params[:search_by] == "email"
      #TODO put checks here that field should not be empty
      #TODO page results here, make it case insensitive
      @users = User.where("email like ? ", "%#{params[:q]}%")
      @query = params[:q]
    elsif params[:search_by] == "name"
      @users = User.where("name like ? ", "%#{params[:q]}%") # changing ==to = for postgres
      @query = params[:q]
    else
      flash.now[:danger] = "Search failed, remember to select a criteria."
      render 'users'
    end

  end
  private
    #Use callbacks to share common setup or constraints between actions.
  def set_user
     @user = User.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :name, :is_admin, :is_root)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user,:html => {:class => 'form'}) do |f| %>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
     <%= f.label :email %>
    <%= f.text_field(:email, class:"form-control") %>
  </div>
    <%if((logged_in? && @user==@current_user)||!logged_in?)%>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field(:password,class:"form-control") %>
    </div>
        <%end%>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field(:name,class:"form-control") %>
  </div>
<%if(logged_in? && logged_in_as_admin?)%>
  <div class="form-group">
    <%= f.label :is_admin %>
    <%= f.check_box :is_admin %>
  </div>
<% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
    </div>
<% end %>

app/views/users/_user_search_box.html.erb
<%= form_tag("/users/search", method: "get") do %>
  <%= label_tag(:q, "Search for members here: ") %>
  <%= text_field_tag(:q) %> <i>*Leave blank to view all</i>
  <br/>
  <%= radio_button_tag(:search_by, "email", checked: true) %>
  <%= label_tag(:search_by_email, "Search by email") %>
  <%= radio_button_tag(:search_by, "name") %>
  <%= label_tag(:search_by_name, "Search by name") %>
  <br/>
  <%= submit_tag "Search Users!", class:"btn btn-primary" %>
<% end %>

app/views/users/_users_common.html.erb
<% if logged_in_as_admin? %>
    <%= render 'users/admin_home' %>
<% else %>
    <%= render 'users/lib_member_home' %>
<% end %>

app/views/users/booking_history.html.erb
<br/>
<p id="notice"><%= notice %></p>
<%if @bookingUser.count == 0%>
    <b>This user has no history!!</b>
<%else%>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Booking Time</th>
        <th>Room</th>
        <!--<th>Cancelled by</th>-->
        <th>Cancelled</th>
        <th>Booked by</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @bookingUser.each do |booking| %>
          <tr>
            <td><%= booking.booking %></td>
            <td><%= (Room.find(booking.room_id)).number %></td>
            <td><%= booking.cancelled %></td>
            <td><%= booking.booked_by%></td>
            <td><%= link_to 'Show', booking %></td>
            <td><%= button_to 'Release', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <%end%>
      </tbody>
    </table>

<%end%>
<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/users/edit.html.erb
<br/>
<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<br/>
<p id="notice"><%= notice %></p>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" />
<h3><span class="label label-primary">Users</span></h3>
<br/>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Is admin</th>
      <th>Is root</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <%if user.is_admin == true%>
        <td><%= "True" %></td>
            <%else%>
            <td><%= "False" %></td>
            <%end%>
        <td><%= user.is_root %></td>
      <%if user.is_admin == true%>
            <td><%= link_to 'Manage Admin', edit_user_path(user) %></td>
            <%else%>
            <td><%= link_to 'Manage Library Member', edit_user_path(user) %></td>
            <%end%>
        <td><%= link_to 'Show', (user) %></td>
        <td><%= link_to 'Booking History', "/users/booking_history/#{user.id}" %></td>
        <%if user.is_root != true && logged_in_as_admin? && user.id!=session[:user_id]%>
        <td><%= button_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="col-sm-3"><%= link_to 'New User', new_user_path %></div>
 <!-- <div class="col-sm-3">%= link_to 'New Room', new_room_path %></div>
    <div class="col-sm-3">%= link_to 'New Booking', new_booking_path %></div>
      <div class="col-sm-3">%= link_to "Login to continue", sessions_new_path %></li></div> -->

app/views/users/new.html.erb
<br/>
<p id="notice"><%= notice %></p>
<%if !logged_in? || logged_in_as_admin?%>
<%= render 'form', user: @user %>
<%else%>
    <h1>You need to admin privileges to do this!</h1>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/search_user.html.erb
<br/>
<% provide(:title, "User search") %>
<%= render 'users/users_common' %>
<div>
<p>
	<%= render 'users/user_search_box' %>
</p>
Displaying search results for "<%= @query %>"
<ul>
  <table class="table table-striped">
	<thead>
	  <tr>
		<th>Member name</th>
		<th>email</th>
		<th>Booking History</th>
		<th>Update member</th>
		<th colspan="3"></th>
	  </tr>
	</thead>


	<tbody>
<% @users.each do |user| %>
		<tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <!--<td>%= button_to "Booking history", "history", method: :get %></td>-->
      <td><%= link_to 'Booking History', "/users/booking_history/#{user.id}" %></td>
	  <td><%= button_to 'Update Member' ,edit_user_path(user), method: :get %></td>
		</tr>
<% end %>
	</tbody>
  </table>
</ul>
</div>

app/views/users/show.html.erb
<div style="margin: 10%">
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Is admin:</strong>
  <%= @user.is_admin %>
</p>

<p>
  <strong>Is root:</strong>
  <%= @user.is_root %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</div>

app/views/users/users.html.erb
<% provide(:title, @current_user.name) %>
<div style="margin: 5%">
<p id="notice"><%= notice %></p>
<%= render 'users/users_common' %>
<br/>
<p>
  <% if logged_in? && logged_in_as_admin? %>
      <%= render 'users/user_search_box' %>
      <br/>
  <% end %>
      <%= render 'rooms/room_search_box' %>

</p>
<br/>
</div>