config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'sessions/new'
  root 'application#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  get    'search'   => 'users#search'
  get    'users/search'   => 'users#search_user'
  get    'rooms/search'   => 'rooms#search_room'
  get 'users/history' => 'users#get_history'
  get '/rooms/schedule_room/:id' => 'rooms#schedule_room'
  get '/users/booking_history/:id' => 'users#booking_history'
  resources :bookings
  resources :rooms
  resources :users
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings
  VALID_ROOMSIZE_REGEX = /(4|6|12)/
  validates :size, presence: true,
            format: { with: VALID_ROOMSIZE_REGEX }
  validates :number, presence: true, uniqueness: true
  VALID_BUILDING_REGEX = /(D.H.Hill|James.B.Hunt)/
  validates :building, presence: true,
            format: { with: VALID_BUILDING_REGEX }
  VALID_Status_REGEX = /(Available)/
  validates :status, presence: true,
            format: { with: VALID_Status_REGEX }
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :schedule_room,:edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  #GET /rooms/1/schedule_room
  def schedule_room
    @bookingsWeek = Booking.where("cancelled =? AND room_id= ? AND booking > ? AND booking < ?",'f',"#{@room.id}",Time.now.beginning_of_day,Time.now.end_of_day ).order(:booking)
  end
  # GET /rooms/1/edit
  def edit
  end
  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @bookingsForRoom = Booking.where("room_id = ?","#{@room.id}");
    @bookingsForRoom.each do|bookie|
      bookie.destroy
    end
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_room
    if params[:search_by] == "Building"
      #TODO put checks here that field should not be empty
      #TODO page results here, make it case insensitive
      @rooms = Room.where("building like ? ", "%#{params[:q]}%")
      @query = params[:q]
    elsif params[:search_by] == "size"
      @rooms = Room.where("size =? ", "#{params[:q]}") # changing ==to = for postgres
      @query = params[:q]
    elsif params[:search_by] == "Number"
      @rooms = Room.where("number =? ", "#{params[:q]}") # changing ==to = for postgres
      @query = params[:q]
    else
      flash.now[:danger] = "Search failed, remember to select a criteria."
      render 'rooms/index'
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:number, :status, :building, :size)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<br/>
<%= form_for(room,:html => {:class => 'form'}) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :number %>
    <%= f.number_field(:number, class:"form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.text_field(:status, class:"form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :building %>
    <%= f.text_field(:building, class:"form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :size %>
    <%= f.number_field(:size, class:"form-control") %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_room_search_box.erb
<%= form_tag("/rooms/search", method: "get") do %>
    <%= label_tag(:q, "Search for rooms here: ") %>
    <%= text_field_tag(:q) %> <i>*Leave blank to view all</i>
    <br/>
    <%= radio_button_tag(:search_by, "Building", checked: true) %>
    <%= label_tag(:search_by_building, "Search by Building") %>
    <%= radio_button_tag(:search_by, "size") %>
    <%= label_tag(:search_by_size, "Search by size") %>
    <%= radio_button_tag(:search_by, "Number") %>
    <%= label_tag(:search_by_size, "Search by number") %>
    <br/>
    <%= submit_tag "Search Rooms!", class:"btn btn-primary" %>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<br/>
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Number</th>
      <th>Building</th>
      <th>Status</th>
      <th>Size</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.number %></td>
        <td><%= room.building %></td>
        <td><%= room.status %></td>
        <td><%= room.size %></td>
        <td><%= link_to 'Show', room %></td>
        <b><td><%= link_to 'View Schedule today', "/rooms/schedule_room/#{room.id}" %></td></b>
        <% if logged_in_as_admin? %>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= button_to 'Destroy', room, method: :delete,'data-no-turbolink' => true, data: { confirm: 'Are you sure?' } %></td>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

app/views/rooms/new.html.erb
<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/schedule_room.html.erb
<br/>
<p id="notice"><%= notice %></p>
<h><b>Today's Bookings:</b></h>
<br/>
<%if @bookingsWeek.count == 0%>
    <b>This room is available at all times today. Go ahead and book!!</b>
 <%else%>
    <% @bookingsWeek.each do |booking| %>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%=(booking.booking.strftime("%H:%M"))%> - <%=(booking.booking + 2.hours).strftime("%H:%M")%></th>
  </tr>
  </thead>

  <tbody>
      <tr>
        <td><h4><span class="label label-danger">Booked</span></h4></td>
      </tr>
  </tbody>
</table>
<%end%>
    <% end %>
<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/rooms/search_room.html.erb
<% provide(:title, "Room search") %>
<br/>
<div>
<p>
	<%= render 'rooms/room_search_box' %>
</p>
Displaying search results for "<%= @query %>"
<ul>
  <table class="table table-striped">
	<thead>
	  <tr>
		<th>Room Number</th>
		<th>Status</th>
		<th>Building</th>
		<th>Size</th>
		<th colspan="3"></th>
	  </tr>
	</thead>


	<tbody>
<% @rooms.each do |room| %>
		<tr>
      <td><%= room.number%></td>
      <td><%= room.status%></td>
      <td><%= room.building%></td>
      <td><%= room.size%></td>
      <% if logged_in_as_admin? %>
          <td><%= button_to "Update Room", edit_room_path(room), method: :get %></td>
          <b><td><%= link_to 'View Schedule for today', "/rooms/schedule_room/#{room.id}" %></td></b>
	  <td><%= button_to 'Delete Room',room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% end %>
          </tr>
<% end %>
	</tbody>
  </table>
</ul>
</div>

app/views/rooms/show.html.erb
<div style="margin: 5% ">
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @room.number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @room.status %>
</p>

<p>
  <strong>Building:</strong>
  <%= @room.building %>
</p>

<p>
  <strong>Size:</strong>
  <%= @room.size %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>
</div>