config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'sessions/new'
  root 'application#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  get    'search'   => 'users#search'
  get    'users/search'   => 'users#search_user'
  get    'rooms/search'   => 'rooms#search_room'
  get 'users/history' => 'users#get_history'
  get '/rooms/schedule_room/:id' => 'rooms#schedule_room'
  get '/users/booking_history/:id' => 'users#booking_history'
  resources :bookings
  resources :rooms
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head style="margin-bottom: auto">
    <%= javascript_include_tag :all, "data-turbolinks-track" => false %>
    <%= csrf_meta_tags %>
    <title><%= yield(:title) %> | Library</title>


    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" />

    <%if(logged_in? && logged_in_as_admin?)%>
        <header class="navbar navbar-fixed-top row" style="margin-bottom: 10px;">
            <nav>
              <ul class="nav nav-pills" style="background-color: #DADADA">
                <li role="presentation"><div class="col-md-8"><h4><span class="label label-success">Welcome <%= @current_user.name %></span></h4></div></li>
                <li role="presentation" ><div class="col-md-3"><%= link_to 'Home', root_path %></div></li>
                <li role="presentation" ><div class="col-md-3"><%= link_to 'New User', new_user_path %></div></li>
                <li role="presentation" > <div class="col-md-3"><%= link_to 'New Room', new_room_path %></div></li>
                <li role="presentation" ><div class="col-md-3"><%= link_to 'New Booking', new_booking_path %></div></li>
                <li role="presentation" ><div class="col-md-3"><%= link_to "Manage Users/View History", users_path %></div></li>
                <li role="presentation" ><div class="col-md-3"><%= link_to "Manage Rooms/View Schedule", rooms_path %></div></li>
                <li role="presentation" ><div class="col-md-3"><%= link_to "Manage Bookings", bookings_path %></div></li>
                <li role="presentation" ><div class="col-md-3"><%= link_to "Edit My Profile", edit_user_path(@current_user.id) %></div></li>
                <li role="presentation"><div class="col-md-6"><span class="glyphicon glyphicon-off" aria-hidden="true"><%= link_to "Logout", logout_path %></span></div></li>
              </ul>
            </nav>
        </header><%end%>
    <%if(logged_in? && !logged_in_as_admin?)%>
        <header class="navbar navbar-fixed-top row" style=" margin-bottom: 10px;">
          <nav>
            <ul class="nav nav-pills" style="background-color: #DADADA">
              <li role="presentation"><div class="col-md-8"><span class="label label-success">Welcome <%= @current_user.name %>  </span></div></li>
              <li role="presentation" ><div class="col-md-3"><%= link_to 'Home', root_path %></div></li>
              <li role="presentation" ><div class="col-md-3"><%= link_to 'New Booking', new_booking_path %></div></li>
              <li role="presentation" ><div class="col-md-3"><%= link_to 'Booking History', "/users/booking_history/#{@current_user.id}"%></div></li>
              <li role="presentation" ><div class="col-md-3"><%= link_to "View Rooms/Schedule", rooms_path %></div></li>
              <li role="presentation" ><div class="col-md-3"><%= link_to "Edit My Profile", edit_user_path(@current_user.id) %></div></li>
              <li role="presentation"><div class="col-md-6"><span class="glyphicon glyphicon-off" aria-hidden="true"><%= link_to "Logout", logout_path %></span></div></li>
            </ul>
          </nav>
        </header>

    <%end%>
  </head>

  <body style="alignment: center">
  <br/>
  <br/>
    <%= yield %>
  </body>
</html>